include gruvbox_dark.conf

term xterm-256color
shell_integration no-cursor
allow_hyperlinks yes
editor nvim

# Cursor trail
cursor_shape block
cursor_blink true
cursor_trail 3
cursor_trail_start_threshold 0
cursor_trail_decay 0.05 0.1

# Terminal Padding
window_padding_width 10

# macos_hide_titlebar yes
macos_option_as_alt yes

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMonoNL Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14
# END_KITTY_FONTS

# Add fallback fonts
symbol_map U+3000-U+303F,U+3040-U+309F,U+30A0-U+30FF,U+FF00-U+FFEF,U+4E00-U+9FA9 Noto Sans Mono CJK JP
symbol_map U+0E00-U+0E7F Tlwg Mono
